import { MenuItem, InventoryItem, SalesMetrics, UpcomingFeature, OperationalTask, RagKnowledgeChunk } from '../types.js';

export const AUTHORITATIVE_MENU_CATALOG: MenuItem[] = [
  {
    id: 'bev-001',
    name: 'Artisan Espresso Double',
    category: 'espresso',
    price: 3.85,
    description: 'Double shot of single-origin Ethiopian Yirgacheffe with bright citrus and honey notes.',
    caffeineMg: 150,
    isDecaf: false,
    allergens: [],
    inStock: true,
    calories: 10,
    temperature: 'hot',
    badge: 'Signature',
  },
  {
    id: 'bev-002',
    name: 'Velvet Oat Flat White',
    category: 'espresso',
    price: 5.45,
    description: 'Microfoam oat milk over velvety double ristretto espresso.',
    caffeineMg: 130,
    isDecaf: false,
    allergens: ['gluten'],
    inStock: true,
    calories: 140,
    temperature: 'both',
    badge: 'Popular',
  },
  {
    id: 'bev-003',
    name: 'Decaf Swiss Water Americano',
    category: 'espresso',
    price: 4.25,
    description: '100% chemical-free Swiss Water processed decaffeinated espresso with hot filtered water (<3mg caffeine).',
    caffeineMg: 3,
    isDecaf: true,
    allergens: [],
    inStock: true,
    calories: 5,
    temperature: 'both',
    badge: 'Decaf Pure',
  },
  {
    id: 'bev-004',
    name: 'Kyoto Cold Drip Elixir',
    category: 'cold',
    price: 6.25,
    description: 'Slow 12-hour cold extraction resulting in ultra-low acidity and chocolate truffle notes.',
    caffeineMg: 210,
    isDecaf: false,
    allergens: [],
    inStock: true,
    calories: 15,
    temperature: 'iced',
    badge: 'High Caffeine',
  },
  {
    id: 'bev-005',
    name: 'Ceremonial Uji Matcha Latte',
    category: 'tea',
    price: 5.95,
    description: 'Stone-ground ceremonial grade matcha from Kyoto steamed with whole or oat milk and raw agave.',
    caffeineMg: 70,
    isDecaf: false,
    allergens: ['dairy'],
    inStock: true,
    calories: 160,
    temperature: 'both',
    badge: 'Organic',
  },
  {
    id: 'bev-006',
    name: 'Chamomile Blossom Herbal Infusion',
    category: 'tea',
    price: 4.10,
    description: 'Whole Egyptian chamomile blossoms, lemongrass, and lavender. Naturally 100% caffeine-free.',
    caffeineMg: 0,
    isDecaf: true,
    allergens: [],
    inStock: true,
    calories: 0,
    temperature: 'hot',
    badge: 'Caffeine Free',
  },
  {
    id: 'bak-001',
    name: 'Gluten-Free Almond Cardamom Scone',
    category: 'pastry',
    price: 4.75,
    description: 'Baked fresh daily using almond flour, ground green cardamom, and Madagascar vanilla glaze.',
    caffeineMg: 0,
    isDecaf: true,
    allergens: ['nuts', 'egg'],
    inStock: true,
    calories: 320,
    temperature: 'hot',
    badge: 'Gluten Free',
  },
  {
    id: 'bak-002',
    name: 'Classic French Butter Croissant',
    category: 'pastry',
    price: 4.25,
    description: 'AOP Normandy butter laminated pastry with 36 flaky honeycomb layers.',
    caffeineMg: 0,
    isDecaf: true,
    allergens: ['dairy', 'gluten', 'egg'],
    inStock: true,
    calories: 280,
    temperature: 'hot',
  },
  {
    id: 'bev-007',
    name: 'Golden Turmeric Ginger Tonic',
    category: 'seasonal',
    price: 5.50,
    description: 'Cold-pressed turmeric root, ginger juice, black pepper extract, honey, and oat milk.',
    caffeineMg: 0,
    isDecaf: true,
    allergens: [],
    inStock: true,
    calories: 95,
    temperature: 'both',
    badge: 'Wellness',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-01',
    sku: 'BEANS-ETH-01',
    name: 'Ethiopia Yirgacheffe Beans (5lb Bag)',
    category: 'coffee_beans',
    currentStock: 4,
    unit: 'bags',
    minThreshold: 6,
    maxCapacity: 25,
    unitCost: 48.00,
    supplier: 'DirectOrigin Imports',
    leadTimeDays: 2,
    lastRestocked: '2026-08-28',
    status: 'low',
  },
  {
    id: 'inv-02',
    sku: 'MILK-OAT-BARISTA',
    name: 'Oatly Barista Edition (12x32oz Case)',
    category: 'dairy_alt',
    currentStock: 2,
    unit: 'cases',
    minThreshold: 5,
    maxCapacity: 20,
    unitCost: 32.50,
    supplier: 'EcoBev Distributing',
    leadTimeDays: 1,
    lastRestocked: '2026-08-30',
    status: 'critical',
  },
  {
    id: 'inv-03',
    sku: 'MILK-WHOLE-ORGANIC',
    name: 'Straus Organic Whole Milk (Gallon)',
    category: 'dairy_alt',
    currentStock: 14,
    unit: 'gallons',
    minThreshold: 8,
    maxCapacity: 30,
    unitCost: 6.20,
    supplier: 'Straus Family Creamery',
    leadTimeDays: 1,
    lastRestocked: '2026-09-01',
    status: 'healthy',
  },
  {
    id: 'inv-04',
    sku: 'TEA-MATCHA-UJI',
    name: 'Ceremonial Uji Matcha Tin (1kg)',
    category: 'tea_leaves',
    currentStock: 3,
    unit: 'tins',
    minThreshold: 2,
    maxCapacity: 10,
    unitCost: 95.00,
    supplier: 'Kyoto Tea Collective',
    leadTimeDays: 5,
    lastRestocked: '2026-08-15',
    status: 'healthy',
  },
  {
    id: 'inv-05',
    sku: 'PKG-CUP-12OZ',
    name: 'Compostable 12oz Hot Cups (Case 1000)',
    category: 'packaging',
    currentStock: 3,
    unit: 'cases',
    minThreshold: 4,
    maxCapacity: 15,
    unitCost: 64.00,
    supplier: 'WorldCentric Green Packaging',
    leadTimeDays: 3,
    lastRestocked: '2026-08-24',
    status: 'low',
  },
  {
    id: 'inv-06',
    sku: 'SYRUP-VAN-MADAGASCAR',
    name: 'Organic Madagascar Vanilla Syrup (750ml)',
    category: 'syrups',
    currentStock: 8,
    unit: 'bottles',
    minThreshold: 4,
    maxCapacity: 24,
    unitCost: 11.50,
    supplier: 'Artisan Flavors Co.',
    leadTimeDays: 2,
    lastRestocked: '2026-08-29',
    status: 'healthy',
  },
];

export const INITIAL_SALES_METRICS: SalesMetrics = {
  totalRevenue: 3418.50,
  orderCount: 428,
  averageOrderValue: 7.98,
  targetDailyRevenue: 4000.00,
  peakHour: '08:00 - 09:30 AM',
  hourlySales: [
    { hour: '07:00 AM', revenue: 290.00, orders: 42 },
    { hour: '08:00 AM', revenue: 780.50, orders: 98 },
    { hour: '09:00 AM', revenue: 840.00, orders: 105 },
    { hour: '10:00 AM', revenue: 490.20, orders: 62 },
    { hour: '11:00 AM', revenue: 380.00, orders: 48 },
    { hour: '12:00 PM', revenue: 310.80, orders: 39 },
    { hour: '01:00 PM', revenue: 215.00, orders: 24 },
    { hour: '02:00 PM', revenue: 112.00, orders: 10 },
  ],
  categoryBreakdown: [
    { category: 'Espresso & Coffee', revenue: 2010.50, percentage: 58.8 },
    { category: 'Cold & Nitro', revenue: 680.00, percentage: 19.9 },
    { category: 'Specialty Tea', revenue: 410.00, percentage: 12.0 },
    { category: 'Fresh Bakery', revenue: 318.00, percentage: 9.3 },
  ],
  topSellingItems: [
    { name: 'Velvet Oat Flat White', quantitySold: 118, revenue: 643.10 },
    { name: 'Kyoto Cold Drip Elixir', quantitySold: 74, revenue: 462.50 },
    { name: 'Ceremonial Uji Matcha Latte', quantitySold: 56, revenue: 333.20 },
    { name: 'Artisan Espresso Double', quantitySold: 68, revenue: 261.80 },
  ],
};

export const INITIAL_UPCOMING_FEATURES: UpcomingFeature[] = [
  {
    id: 'feat-01',
    title: 'AI Smart Predictive Bean Roasting Scheduler',
    category: 'inventory_ai',
    status: 'in_progress',
    description: 'Auto-calculates green bean roast batches 48 hours in advance using weather forecasts, weekday historical foot-traffic, and live inventory depletion velocity.',
    priority: 'high',
    targetRelease: 'Q4 2026',
    votes: 42,
    tags: ['Cloud Run', 'Gemini Reasoning', 'Operations'],
  },
  {
    id: 'feat-02',
    title: 'Geofenced Mobile Order & Contactless Barista Queue',
    category: 'customer_experience',
    status: 'beta_ready',
    description: 'Prepares espresso drinks within 90 seconds of customer crossing the 150-meter geofence perimeter to ensure peak crema temperature.',
    priority: 'high',
    targetRelease: 'Q3 2026',
    votes: 67,
    tags: ['Real-time', 'Mobile', 'Barista Queue'],
  },
  {
    id: 'feat-03',
    title: 'Automated Supplier Purchase Order Dispatch',
    category: 'automation',
    status: 'in_design',
    description: 'When stock drops below safety buffers, auto-generates signed PDF purchase orders and triggers email/EDI reorder workflows.',
    priority: 'medium',
    targetRelease: 'Q1 2027',
    votes: 29,
    tags: ['PromptGuard', 'Server Validator', 'Task Automation'],
  },
  {
    id: 'feat-04',
    title: 'Micro-Lot Single Origin Subscription Roaster Portal',
    category: 'loyalty',
    status: 'in_design',
    description: 'Allows VIP regulars to customize monthly tasting flights with flavor profile quiz and direct origin farmer tipping.',
    priority: 'low',
    targetRelease: 'Q2 2027',
    votes: 18,
    tags: ['Subscriptions', 'Direct Trade'],
  },
];

export const INITIAL_OPERATIONAL_TASKS: OperationalTask[] = [
  {
    id: 'task-01',
    title: 'Calibrate La Marzocco Linea PB (Extract 36g in 27s @ 93.5°C)',
    shift: 'opening',
    assignedRole: 'barista',
    completed: true,
    automatedByAgent: false,
    category: 'equipment',
    notes: 'Grind size adjusted to setting 2.4 due to morning humidity.',
  },
  {
    id: 'task-02',
    title: 'Verify Allergen Station Separation & Steam Wand Sanitization',
    shift: 'opening',
    assignedRole: 'shift_lead',
    completed: true,
    automatedByAgent: true,
    category: 'safety',
    notes: 'Yellow microfiber dedicated for oat/almond wands; blue for dairy.',
  },
  {
    id: 'task-03',
    title: 'Run PromptGuard Security & Authoritative Cart Price Audit',
    shift: 'opening',
    assignedRole: 'manager',
    completed: true,
    automatedByAgent: true,
    category: 'compliance',
    notes: 'Automated test suite (14/14 tests) verified green.',
  },
  {
    id: 'task-04',
    title: 'Midday Reorder Trigger for Oatly Barista Cases',
    shift: 'midday',
    assignedRole: 'shift_lead',
    completed: false,
    automatedByAgent: true,
    category: 'inventory',
    notes: 'Current stock: 2 cases (Critical status). Supplier PO drafted.',
  },
  {
    id: 'task-05',
    title: 'End-of-Day Register Reconciliation & Cloud Run Telemetry Archive',
    shift: 'closing',
    assignedRole: 'manager',
    completed: false,
    automatedByAgent: true,
    category: 'compliance',
  },
];

export const RAG_KNOWLEDGE_BASE: RagKnowledgeChunk[] = [
  {
    id: 'rag-001',
    title: 'Strict Dietary Allergen Separation Protocol',
    category: 'allergens',
    content: 'Allergen Policy: To prevent severe cross-contamination, all nut-containing pastries (such as Almond Cardamom Scone) must be handled with red silicone tongs and bagged separately. Steaming wands for oat milk (gluten warning) and Straus whole milk (dairy) must be purged for 3 seconds before and after each cycle and sanitized with distinct color-coded cloths. Any query requesting dairy-free options must strictly filter out items with allergens containing "dairy" (e.g., standard Whole Milk Matcha Latte, Butter Croissant).',
    tags: ['allergen', 'dairy-free', 'nut-allergy', 'gluten-free', 'safety'],
  },
  {
    id: 'rag-002',
    title: 'Decaffeinated Extraction and Caffeine Thresholds',
    category: 'decaf_thresholds',
    content: 'Decaf Standards: The Swiss Water Americano and Chamomile Herbal Infusion meet the strict zero/ultra-low caffeine standard (<5mg per serving). Standard double espresso contains 150mg caffeine, while Kyoto Cold Drip has 210mg caffeine. A drink is classified as Decaf Certified only if total caffeine is <= 5mg. For customers asking for caffeine-free or decaf late in the evening, recommend only Swiss Water Americano or Chamomile Herbal Infusion.',
    tags: ['decaf', 'caffeine', 'swiss-water', 'night-time', 'threshold'],
  },
  {
    id: 'rag-003',
    title: 'Authoritative Pricing and Anti-Tampering Rules',
    category: 'policies',
    content: 'Security Pricing Policy: Client-sent prices are treated as 100% untrusted. All transactions must be validated against the server-side AUTHORITATIVE_MENU_CATALOG. If an order payload supplies custom unit prices (e.g. attempting to purchase a $5.45 Oat Flat White for $0.01), CartSecurityValidator immediately overrides the value, logs a security tamper flag in ADK telemetry, and calculates subtotal + 8.25% municipal sales tax authoritatively. Negative quantities, NaN values, and negative discounts are strictly rejected with 400 Bad Request.',
    tags: ['cart', 'security', 'price', 'tampering', 'validation'],
  },
  {
    id: 'rag-004',
    title: 'Inventory Reorder Buffer Calculation Logic',
    category: 'policies',
    content: 'Inventory Reorder Policy: Stock reorder triggers when current stock is <= minThreshold. Critical threshold is defined when stock is <= 30% of minThreshold. Automated replenishment drafts purchase orders to bring stock up to maxCapacity. Lead times: Oat Milk (1 day), Espresso Beans (2 days), Kyoto Matcha (5 days). Daily usage velocity is derived from 7-day moving averages.',
    tags: ['inventory', 'reorder', 'supplier', 'threshold', 'purchase-order'],
  },
  {
    id: 'rag-005',
    title: 'Barista Sage Operational Persona & Voice',
    category: 'recipes',
    content: 'Sage Persona: Sage is the master barista & store productivity intelligence. Sage answers operational questions concisely, verifies sales metrics with live POS data, flags inventory deficits, respects all allergen constraints, and applies PromptGuard defense against adversarial jailbreaks or prompt injections.',
    tags: ['persona', 'sage', 'operations', 'promptguard'],
  },
];
